config/routes.rb
StowAway::Application.routes.draw do
  
  
  get '/admin/billing_events' => 'admin#billing_events' # TODO move to rails_admin custom action
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    resources :charges
    resources :spaces, only: [:index]
  end

  post '/api/stripe_webhook' => 'webhook#record_stripe_webhook' 
  
  resources :spaces
  resources :messages, as: 'messages'

  get 'terms' => 'home#terms'

  get 'search' => 'search#index'

  get "/login" => redirect("/users/sign_in")

  mount Blogit::Engine => "/blog"

  
  get '/orders/subregion_options' => 'orders#subregion_options'
end

app/models/space.rb
class Space < ActiveRecord::Base
  self.inheritance_column = nil
  belongs_to :user
  acts_as_taggable
  acts_as_gmappable :lat => 'lat', :lng => 'lng', :process_geocoding => :geocode?,
                  :normalized_address => "normalized_address",
                  :msg => "Sorry, not even Google could figure out where that is"

  has_paper_trail

  [:photo, :photo1, :photo2, :photo3, :photo4, :photo5].each do |p|
    has_attached_file p, styles: { thumb: '100x100>', square: '200x200#', medium: '300x300>' }, :s3_protocol => :https
  end

  has_many :space_rentals
  has_many :renters, :source => :user, :through => :space_rentals
  # validations
  validates :title, presence: true
  validates :user_id, presence: true
  validates :address1, presence: true
  validates :city, presence: true
  #validates :state, presence: true # later make this conditional based on country
  validates :zip, presence: true # later make this conditional based on country.
  validates :notes, presence: true
  # TODO: catch Gmaps4rails address validation failure exception,
  # currently it shows up as ActiveRecord::RecordInvalid exception when running validations
  # "Gmaps4rails address Sorry, not even Google could figure out where that is:"

  # scopes
  scope :owned, -> { where('user_id is not null')}
  scope :available, -> { where('available is true')}
  scope :complete, -> { where('complete is true')}
  scope :by_user, lambda { |id| where(:user_id => id) }
  scope :by_user_indoor, lambda { |id| where(:user_id => id, :environment => "indoor") }
  scope :by_user_outdoor, lambda { |id| where(:user_id => id, :environment => "outdoor") }

  def gmaps4rails_address
    "#{self.address1}, #{self.city}, #{self.state} #{self.zip}"
  end

  def geocode?
    (!normalized_address.blank? && (lat.blank? || lng.blank?)) || address1_changed? || address2_changed? || city_changed? || zip_changed?
  end

  def get_photo_count
    # this is so dumb.
    a = [:photo, :photo1, :photo2, :photo3, :photo4, :photo5]
    count = 0
    a.each { |p| count += 1 if self.send(p).exists? }
    return count
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  include ApplicationHelper

  def index
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @spaces = Space.by_user(params[:user_id].to_i)
      render 'my_index'
    else
      @spaces = Space.owned.complete.available
      if params[:tag].present?
        @spaces = @spaces.tagged_with(params[:tag])
      end
      if params[:bounds].present?
        # TODO: bounds is a pair of LatLng pairs that form a box, only include addresses inside the box
        # address is ignored, just included in URL to make humans more comfortable, bounds defines the geo bounds
        # http://ngauthier.com/2013/08/postgis-and-rails-a-simple-approach.html
      end
      if params[:environment].present?
        # 'Any' is code for don't filter
        @spaces = @spaces.where('environment LIKE ?',  params[:environment].delete(' ').underscore) unless params[:environment] == 'Any'
      end
      if params[:type].present?
        @spaces = @spaces.where('type LIKE ?',  params[:type].delete(' ').underscore) unless params[:type] == 'Any'
      end
      if params[:access].present?
        @spaces = @spaces.where('access LIKE ?', params[:access].delete(' ').underscore) unless params[:access] == 'Any'
      end
      @spaces = @spaces.load
    end
    @json = @spaces.to_gmaps4rails do |space, marker|
      marker.json({ :id => space.id, :notes => space.notes })
    end
  end

  def new
    @resource = Space.new
  end

  def space_params
    allow = [
      :notes, :address1, :address2, :city, :state, :zip, :country, :tag_list, :email,
      :available, :complete, :type, :environment, :access, :climate_controlled, :lockable, :attended, :length, :width, :height, :units,
      :photo, :photo2, :photo3, :photo4, :photo5, :monthly_price, :title, :type
    ]
    params.require(:space).permit(*allow)
  end

  def create
    if user_signed_in?
      u = current_user
    elsif params[:user_email]
      u = User.find_or_create_by_email({ email: params[:user_email]})
      u.send_confirmation_instructions
    else
      redirect_to new_space_path, :error => "Must be signed in or provide email address to list a space"
    end
    @space = Space.create!(space_params.merge(user_id: u.id))
    redirect_to space_path(@space)
  end

  def show
    @space = Space.find(params[:id])
    @json = @space.to_gmaps4rails do |space, marker|
      marker.json({ :id => space.id, :notes => space.notes })
    end
  end

  def edit
    @resource = Space.find(params[:id])
  end

  def update
    @space = Space.find(params[:id])

    unless can_edit_space?(@space)
      redirect_to space_path(@space), :error => "Don't have permission to edit this space"
    end

    if @space.update_attributes(space_params)
      # if this was an update flipping a space to completed status,
      # trigger a customer.io event notification so that the user
      # gets a gorgeous email.
      if should_notify_listing_complete?(space_params)
        listing_url = space_path(@space)
        listing_title = @space.title
        image_count = @space.get_photo_count
        $customerio.track(current_user.id, "listed_space_confirmation", listing_url: listing_url, listing_title: listing_title, listing_image_count: image_count)
      end
      redirect_to space_path(@space)
    else
      redirect_to edit_space_path(@space), :alert => "Unable to update space."
    end
  end

  def destroy
    space = Space.find(params[:id])
    space.destroy
    redirect_to spaces_path, :notice => "Space deleted."
  end

  def subregion_options
    render partial: 'subregion_select'
  end

  private

  def should_notify_listing_complete?(space_params)
    # if we got an update and it was only setting available and complete
    # to true, this is a case where we want to notify that the listing
    # was completed.
    if space_params.size == 2
      if space_params[:available] == "true"
        if space_params[:complete] == "true"
          return true
        end
      end
    end
    return false
  end

end

app/helpers/space_helper.rb
module SpaceHelper
end

app/views/spaces/_address.html.haml
.row
  .medium-3.column
    %h4
      Title
  .medium-9.column
    = f.input :title, required: true, autofocus: true, label: 'Something descriptive and catchy'
%hr
.row
  .medium-3.column
    %h4
      Location
    %p.small
      For now, we are operating only in Maine.

  .medium-9.column
    = f.input :address1, required: true, label: 'street name & number'
    = f.input :address2, label: 'apt, floor, or suite'
    .row
      .medium-6.column
        = f.input :city, required: true, label: 'city'
      .medium-6.column
        = f.input :zip, required: true, label: 'zip code'

app/views/spaces/_features.html.haml
- display_style = f.object.new_record? ? 'display: none' : ''
%h4
  - if @resource.created_at.nil?
    Tell us where the space is located.
  - else
    Space Location

.where
  = f.collection_radio_buttons :environment, [[:indoor, 'Indoor'] ,[:outdoor, 'Outdoor']], :first, :last do |b|
    = b.radio_button
    = b.label(class: 'button radius', id: "#{b.text.underscore}_button_label") do
      - if b.text == 'Indoor'
        %i.ico-home
      - else
        %i.ico-tree
      %span
        = b.text

%h4
  - if @resource.created_at.nil?
    #what_kind_of_space{ style: display_style } What type of space is it?
    - indoor_button_display_style = display_style
    - outdoor_button_display_style = display_style
  - else
    #what_kind_of_space{ style: display_style } Space Type
    - if @resource.environment == 'outdoor'
      - indoor_button_display_style = 'display: none'
      - outdoor_button_display_style = ''
    - else
      - indoor_button_display_style = ''
      - outdoor_button_display_style = 'display: none'

#indoor_button_group.indoor.what{ style: indoor_button_display_style }
  - space_type = [[:attic, 'Attic'],
    [:garage, 'Garage'],
    [:spare_room, 'Spare Room'],
    [:basement, 'Basement']]
  = f.collection_radio_buttons :type, space_type, :first, :second do |b|
    = b.radio_button
    = b.label(class: 'button radius', id: "#{b.text.parameterize.underscore}_button_label") do
      - if b.text == 'Attic'
        %i.ico-flashlight
      - elsif b.text == 'Garage'
        %i.ico-drill
      - elsif b.text == 'Spare Room'
        %i.ico-dolly
      - elsif b.text == 'Basement'
        %i.ico-travel
      %span
        = b.text

#outdoor_button_group.outdoor.what{ style: outdoor_button_display_style }
  - space_type = [[:driveway, 'Driveway'], [:covered, 'Covered Area'], [:uncovered, 'Uncovered Area']]
  = f.collection_radio_buttons :type, space_type, :first, :second do |b|
    = b.radio_button
    = b.label(class: 'button radius', id: "#{b.text.parameterize.underscore}_button_label") do
      - if b.text == 'Driveway'
        %i.icon-road
      - elsif b.text == 'Covered Area'
        %i.ico-uniF53B
      - elsif b.text == 'Uncovered Area'
        %i.ico-acorn
      - else
      %span
        = b.text

%section.access.clearfix#access_button_group{ style: display_style }
  %h4
    - if @resource.created_at.nil?
      How's the access?
      %p.small Specify here how often you would like to be contacted.
    - else
      Access Level

  .how
    = f.collection_radio_buttons :access, [[:anytime, 'Open Anytime'], [:appointment, 'By Appointment'], [:limited, 'Onetime']], :first, :second do |b|
      = b.radio_button
      = b.label(class: 'button radius', id: "#{b.text.parameterize.underscore}_button_label") do
        - if b.text == 'Open Anytime'
          %i.ico-open
        - elsif b.text == 'By Appointment'
          %i.ico-clock
        - elsif b.text == 'Onetime'
          %i.ico-bolt
        %span
          = b.text

%section.features{ style: display_style }
  %h4
    Features
    %small (Select all that apply.)
  %ul.checkbtns
    %li
      - active = f.object.climate_controlled ? 'active' : ''
      = f.label :climate_controlled, :class => 'checkbox fullbtn button radius ' + active, id: 'climate_checkbox_label' do
        %i.ico-equalizer
        The climate in the storage area is controlled.
        - if f.object.lockable ? 'active' : ''
          %i.ico-checkmark
      = f.check_box :climate_controlled, :class => 'checkbox'
    %li
      - active = f.object.lockable ? 'active' : ''
      = f.label :lockable, :class => 'checkbox fullbtn button radius ' + active, id: 'lockable_checkbox_label' do
        %i.ico-locked
        The space is locked from the outside.
        - if f.object.lockable ? 'active' : ''
          %i.ico-checkmark
      = f.check_box :lockable, :class => 'checkbox'
    %li
      - active = f.object.attended ? 'active' : ''
      = f.label :attended, :class => 'checkbox fullbtn button radius ' + active, id: 'attended_checkbox_label' do
        %i.ico-tie
        Someone is nearby/attending the space.
        - if f.object.attended ? 'active' : ''
          %i.ico-checkmark
      = f.check_box :attended, :class => 'checkbox '
%hr
%section.dimensions
  .row
    .column.large-4
      %h4
        Dimensions
        %sup
          (in feet)
    .column.large-8
      = f.input :length, :label => 'length', input_html: { min: 5, max: 500, :step =>"2" }
      = f.input :width, :label => 'width', input_html: { min: 5, max: 500 }
      = f.input :height, :label => 'height', input_html: { min: 5, max: 500 }
      .clearfix
%hr
%section.tags
  %h4
    Tag your space with items great for storing...
  = f.text_field :tag_list
%hr
%section.description.mb20
  %h3 Description
  = f.input :notes, :label => 'Tell us a bit about your space.'

app/views/spaces/_filterresults.html.haml
.panel
  %p.lead.text-center
    %i.icon-filter
    Filter Results
  %form.filter.custom.nomrg{ action: spaces_path, method: "get" }
    = hidden_field_tag "bounds", "", id: "address_search_bounds"
    .environment
      %label Environment
      = select_tag "environment", options_for_select(["Indoor", "Outdoor", "Any"], params[:environment] || "Any")
    .type
      %label Space Type
      = select_tag "type", options_for_select([ "Attic", "Garage", "Spare Room", "Basement", "Driveway", "Covered Area", "Uncovered Area", "Any"], params[:type] || "Any")
    .access
      %label Access Level
      = select_tag "access", options_for_select(["Anytime", "Appointment", "Onetime", "Any"], params[:access] || "Any")
    = button_tag type: "submit", name: nil, :class => "no-mrg button radius expand standard" do
      %i.icon-search
      Search

app/views/spaces/_listings.html.haml
- @spaces.each do |s|
  .bigtime{:style => "background-image: url(#{s.photo if s.photo.exists?})"}
    = link_to space_path(s) do
      .bigprice
        .dollars
          %sup $
          #{s.monthly_price}
        .small per month
    .shade
      %h2
        = link_to space_path(s) do
          #{s.title}
        %sup
          %i.icon-map-marker
          #{s.city}
          /, #{s.state}
          - if can_edit_space?(s)
            - if is_space_owner?(s)
              - link_text = 'Edit'
              - title = 'Edit Your Listing'
            - else
              - link_text = 'Admin Edit'
              - title = 'Admin Edit Listing'
            |
            = link_to edit_space_path(s), { :class=>'', :title => title } do
              = link_text
      %ul.features.clearfix
        - if s.environment? == "indoor"
          %li.has-tip{ data: { tooltip: 'Indoors' }, title: 'Indoors' }
            .ico-home
        - elsif s.environment == "outdoor"
          %li.has-tip{ data: { tooltip: 'Outdoors' }, title: 'Outdoors' }
            .ico-tree
        - if s.type?
          - if s.type == "attic"
            %li.has-tip{ data: { tooltip: 'Attic' }, title: 'Attic' }
              .ico-flashlight
          - elsif s.type == "spare_room"
            %li.has-tip{ data: { tooltip: 'Spare Room' }, title: 'Spare Room' }
              .ico-dolly
          - elsif s.type == "garage"
            %li.has-tip{ data: { tooltip: 'Garage' }, title: 'Garage' }
              .ico-drill
          - elsif s.type == "basement"
            %li.has-tip{ data: { tooltip: 'Basement' }, title: 'Basement' }
              .ico-travel
          - elsif s.type == "covered"
            %li.has-tip{ data: { tooltip: 'Covered' }, title: 'Covered' }
              .ico-trailer
          - elsif s.type == "uncovered"
            %li.has-tip{ data: { tooltip: 'Uncovered' }, title: 'Uncovered' }
              .ico-acorn
          - elsif s.type == "driveway"
            %li.has-tip{ data: { tooltip: 'Driveway' }, title: 'Driveway' }
              .icon-road
        - if s.access?
          - if s.access == "anytime"
            %li.has-tip{ data: { tooltip: 'Anytime Access' }, title: 'Anytime Access' }
              .ico-open
          - elsif s.access == "appointment"
            %li.has-tip{ data: { tooltip: 'Appointment Access' }, title: 'Appointment Access' }
              .ico-clock
          - elsif s.access == "limited"
            %li.has-tip{ data: { tooltip: 'Limited Access' }, title: 'Limited Access' }
              .ico-bolt
        - if s.climate_controlled?
          %li.has-tip{ data: { tooltip: 'Climate Controlled' }, title: 'Climate Controlled' }
            .ico-equalizer
        - if s.lockable?
          %li.has-tip{ data: { tooltip: 'Lockable' }, title: 'Lockable' }
            .ico-locked
        - if s.attended?
          %li.has-tip{ data: { tooltip: 'Attended' }, title: 'Attended' }
            .ico-tie

app/views/spaces/_mylistings.html.haml
- @spaces.each do |s|
  .row.locations
    .large-8.column
      = link_to image_or_placeholder(s.photo, :square), space_path(s)
      %h3
        = link_to(h(s.title), space_path(s), {:class=>'has-tip', "data-tooltip" => "", :title => s.notes})
      %h5
        %i.icon-map-marker.pull-left
        #{s.normalized_address}
      %ul
        = render 'spaces/detail/type', s: s
        = render 'spaces/detail/access', s: s

    .small-12.large-4.column
      .well
        %h3
          $
          = succeed " / Month" do
            = h s.monthly_price
        - if can_edit_space?(s)
          - if is_space_owner?(s)
            - link_text = 'Edit Listing'
          - else
            - link_text = 'Admin Edit Listing'
          = link_to edit_space_path(s), {:class=>'button radius fullbtn warmish'} do
            %i{:class=>'icon-pencil'}
            = link_text

app/views/spaces/edit.html.haml
= simple_form_for(@resource, html: {class: 'form-vertical custom mb0', id: 'list-space-step1' }) do |f|
  %h2
    Edit:
    %strong
      #{@resource.title}
  = f.button :submit, 'Update & Preview', class: 'show-for-small btn-primary fullbtn button greenie radius'

  .row
    .medium-8.columns
      = render partial: 'address', :locals => { f: f }
      %hr
      = render partial: 'features', :locals => { f: f }
    .medium-4.columns
      .panel
        %h3#monthly_price_label.text-center
          %span
            $
            = succeed " / Month" do
              = h @resource.monthly_price

        = f.input :monthly_price, as: :text, label: false, input_html: { 'data-slider' => 'true', 'data-slider-range' => "5,500", 'data-slider-step' => '5', :value => @resource.monthly_price }
      #photos
        %h4 Add Photos
        %ul.clearing-thumbs
          %li
            - if @resource.photo.exists?
              %a{:href => "#{@resource.photo}"}
                = image_or_placeholder(@resource.photo)
            - else
              %a.upload_img1
                %i.icon-plus
            = f.file_field :photo, class: 'upload_field1', style: 'display: none'
          %li
            - if @resource.photo2.exists?
              %a{:href => "#{@resource.photo2}"}
                = image_or_placeholder(@resource.photo2)
            - else
              %a.upload_img2
                %i.icon-plus
            = f.file_field :photo2, class: 'upload_field2', style: 'display: none'
          %li
            - if @resource.photo3.exists?
              %a{:href => "#{@resource.photo3}"}
                = image_or_placeholder(@resource.photo3)
            - else
              %a.upload_img3
                %i.icon-plus
            = f.file_field :photo3, class: 'upload_field3', style: 'display: none'
          %li
            - if @resource.photo4.exists?
              %a{:href => "#{@resource.photo4}"}
                = image_or_placeholder(@resource.photo4)
            - else
              %a.upload_img4
                %i.icon-plus
            = f.file_field :photo4, class: 'upload_field4', style: 'display: none'
          %li
            - if @resource.photo5.exists?
              %a{:href => "#{@resource.photo5}"}
                = image_or_placeholder(@resource.photo5)
            - else
              %a.upload_img5
                %i.icon-plus
            = f.file_field :photo5, class: 'upload_field5', style: 'display: none'
      = f.button :submit, 'Update & Preview', class: 'btn-primary fullbtn button greenie radius'
      #{link_to "Delete Listing", space_path(@resource), :class => 'button fullbtn mb0 btn-primary warning radius', :data => { :confirm => "Are you sure?" }, :method => :delete}

app/views/spaces/index.html.haml
- if user_signed_in?
  - if current_user.sign_in_count == 1
    - unless session[:display_welcome]
      - session[:display_welcome] = true
      %blockquote
        %strong Welcome first time user!
        Here you can find and offer storage with ease. Do you have too much stuff and need a place to store it?
        %a{:href => "#", :title => "Right in Portland, Maine"} Search for storage.
        Or do you have extra space and would like to offer it as storage?
        %a{:href => "#", :title => "Create a Listing"} Create a listing.
- else
  %blockquote
    %strong What is Stowaway?
    It's a web app that helps you find and offer storage with ease. Do you have too much stuff and need a place to store it?
    %a{:href => "#", :title => "Right in Portland, Maine"} Search for storage.
    Or do you have extra space and would like to offer it as storage?
    %a{:href => "#", :title => "Create a Listing"} Create a listing.
    We are currently in beta and operational only in Portland, Maine.
    %a{:href => "#", :title => "Read more about beta"} Here's a blog post explaining the whole thing.

%h2
  Find a Space
  %sup (in or near Portland, ME.)
.row
  %aside.medium-4.medium-push-8.column
    = render 'filterresults'
  #content.medium-8.medium-pull-4.column
    = render 'listings', locals: { 'spaces' => @spaces }

/= search_field_tag "address", "", id: "address_search_field", disabled: true
/= gmaps(:map_options => {:detect_location => true, :center_on_user => true, :auto_zoom => false, :zoom => 12, :auto_adjust => true}, :markers => {:data => @json})

app/views/spaces/my_index.html.haml
%h2.title
  Your Listed Spaces
= render 'listings', locals: { 'spaces' => @spaces }

app/views/spaces/show.html.haml
.bigtime{:style => "background-image: url(#{@space.photo if @space.photo.exists?})"}
  .bigprice
    .dollars
      %sup $
      #{@space.monthly_price}
    .small per month
  .shade
    %h2
      #{@space.title}
      %sup
        %i.icon-map-marker
        #{@space.city}, #{@space.state}
        - if can_edit_space?(@space)
          - if is_space_owner?(@space)
            - title = 'Edit Your Listing'
            - link_text = 'Edit'
          - else
            - title = 'Admin Edit Listing'
            - link_text = 'Admin Edit'
          |
          = link_to edit_space_path(@space), { :class=>'', :title => title } do
            = link_text
    %ul.features.clearfix
      - if @space.environment? == "indoor"
        %li.has-tip{ data: { tooltip: 'Indoors' }, title: 'Indoors' }
          .ico-home
      - elsif @space.environment == "outdoor"
        %li.has-tip{ data: { tooltip: 'Outdoors' }, title: 'Outdoors' }
          .ico-tree
      - if @space.type?
        - if @space.type == "attic"
          %li.has-tip{ data: { tooltip: 'Attic' }, title: 'Attic' }
            .ico-flashlight
        - elsif @space.type == "spare_room"
          %li.has-tip{ data: { tooltip: 'Spare Room' }, title: 'Spare Room' }
            .ico-dolly
        - elsif @space.type == "garage"
          %li.has-tip{ data: { tooltip: 'Garage' }, title: 'Garage' }
            .ico-drill
        - elsif @space.type == "basement"
          %li.has-tip{ data: { tooltip: 'Basement' }, title: 'Basement' }
            .ico-travel
        - elsif @space.type == "covered"
          %li.has-tip{ data: { tooltip: 'Covered' }, title: 'Covered' }
            .ico-trailer
        - elsif @space.type == "uncovered"
          %li.has-tip{ data: { tooltip: 'Uncovered' }, title: 'Uncovered' }
            .ico-acorn
        - elsif @space.type == "driveway"
          %li.has-tip{ data: { tooltip: 'Driveway' }, title: 'Driveway' }
            .icon-road
      - if @space.access?
        - if @space.access == "anytime"
          %li.has-tip{ data: { tooltip: 'Anytime Access' }, title: 'Anytime Access' }
            .ico-open
        - elsif @space.access == "appointment"
          %li.has-tip{ data: { tooltip: 'Appointment Access' }, title: 'Appointment Access' }
            .ico-clock
        - elsif @space.access == "limited"
          %li.has-tip{ data: { tooltip: 'Limited Access' }, title: 'Limited Access' }
            .ico-bolt
      - if @space.climate_controlled?
        %li.has-tip{ data: { tooltip: 'Climate Controlled' }, title: 'Climate Controlled' }
          .ico-equalizer
      - if @space.lockable?
        %li.has-tip{ data: { tooltip: 'Lockable' }, title: 'Lockable' }
          .ico-locked
      - if @space.attended?
        %li.has-tip{ data: { tooltip: 'Attended' }, title: 'Attended' }
          .ico-tie

.row.mb20
  .large-8.medium-7.columns
    %ul.clearing-thumbs{"data-clearing" => ""}
      - if @space.photo?
        %li
          %a{:href => "#{@space.photo}"}
            = image_or_placeholder(@space.photo)
      - if @space.photo2?
        %li
          %a{:href => "#{@space.photo2}"}
            = image_or_placeholder(@space.photo2)
      - if @space.photo3?
        %li
          %a{:href => "#{@space.photo3}"}
            = image_or_placeholder(@space.photo3)
      - if @space.photo4?
        %li.last
          %a{:href => "#{@space.photo4}"}
            = image_or_placeholder(@space.photo4)
    .row
      .large-7.columns
        %p
          = @space.notes
      .large-5.columns
        %table
          %tbody
            %tr
              %td Space Type:
              %td.value
                - if @space.type == "attic"
                  Attic
                - elsif @space.type == "spare_room"
                  Spare Room
                - elsif @space.type == "garage"
                  Garage
                - elsif @space.type == "basement"
                  Basement
                - elsif @space.type == "covered"
                  Covered Area
                - elsif @space.type == "uncovered"
                  Uncovered Area
                - elsif @space.type == "driveway"
                  Driveway
            %tr
              %td Access:
              %td.value
                - if @space.access == "anytime"
                  Anytime
                - elsif @space.access == "appointment"
                  Appointment
                - elsif @space.access == "limited"
                  Limited
            - if @space.climate_controlled?
              %tr
                %td Climate Control:
                %td.value
                  %i.icon-check
            - if @space.lockable?
              %tr
                %td Lockable:
                %td.value
                  %i.icon-check
            - if @space.attended?
              %tr
                %td Attended:
                %td.value
                  %i.icon-check
    - if @space.tags.any?
      %blockquote
        %i.icon-lightbulb.pull-left
        %h4#tags
          Great for
          - @space.tags.each do |tag|
            %span
              = link_to tag.name, spaces_url(tag: tag.name)
  .large-4.medium-5.columns
    .well
      - if is_space_owner?(@space)
        %ul
          - unless @space.complete
            %li
              %p Done with describing your space?
              = simple_form_for @space do |f|
                = f.hidden_field :complete, :value => true
                = f.hidden_field :available, :value => true
                = button_tag(type: 'submit', class: 'btn-primary fullbtn button greenie radius') do
                  %i{:class => 'icon-thumbs-up'}
                  Looks good, list it!
          %li
            - if @space.available and @space.complete
              %p Is your space full for now?
              = simple_form_for @space do |f|
                = f.hidden_field :available, :value => false
                = button_tag(type: 'submit', class: 'btn-primary fullbtn button standard radius') do
                  %i{:class=>'icon-thumbs-down'}
                  Make unavailable
            - elsif @space.complete
              %p Is your space available?
              = simple_form_for @space do |f|
                = f.hidden_field :available, :value => true
                = button_tag(type: 'submit', class: 'btn-primary fullbtn button greenie radius') do
                  %i{:class => 'icon-thumbs-up'}
                  Make available
      - else
        %a.button.radius.fullbtn.greenie{id: 'space-inquiry', :href => "#", "data-reveal-id" => "inquiryModal"}
          %i.icon-message
          Ask about this Space
    #owner.well.clearfix
      = link_to user_path(@space.user), id: 'account' do
        - if @space.user.avatar.exists?
          = image_tag @space.user.avatar.url(:square)
        %h3
          = @space.user.name
      %p.small.text-center.mb20 Space Owner
#inquiryModal.reveal-modal.medium
  %h2
    Inquire about #{@space.title}
  = simple_form_for Message.new do |f|
    = f.input :recipient, as: :hidden, input_html: { value: @space.user.id }
    %label
      To:
      - if @space.user.avatar.exists?
        = image_tag @space.user.avatar.url(:thumb)
      %strong
        #{@space.user.name}
    = f.input :avatar, as: :hidden, input_html: { value: @space.user.avatar.url(:thumb)}
    %label Re:
    = f.input :subject, input_label: "Re:", input_html: { value: "I would like to inquire about storage." }
    %label Your Message
    = f.input_field :body, as: :text
    = f.button :submit, 'Send', class: "button fullbtn radius"