config/routes.rb
StowAway::Application.routes.draw do
  
  
  get '/admin/billing_events' => 'admin#billing_events' # TODO move to rails_admin custom action
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    resources :charges
    resources :spaces, only: [:index]
  end

  post '/api/stripe_webhook' => 'webhook#record_stripe_webhook' 
  
  resources :spaces
  resources :messages, as: 'messages'

  get 'terms' => 'home#terms'

  get 'search' => 'search#index'

  get "/login" => redirect("/users/sign_in")

  mount Blogit::Engine => "/blog"

  
  get '/orders/subregion_options' => 'orders#subregion_options'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :invitation_pending, -> { where(sign_in_count: 0, invitation_sent_at: nil) }

  has_many :blog_posts, :as => "blogger", :class_name => "Blogit::Post"
  has_paper_trail
  acts_as_messageable

  has_attached_file :avatar, styles: {
    thumb: '50x50>',
    square: '200x200#',
    medium: '300x300>'
  }, :s3_protocol => :https

  has_many :space_rentals
  has_many :rentals, :source => :space, :through => :space_rentals

  strip_attributes :collapse_spaces => true
  validates :email, :uniqueness => { :case_sensitive => false }
  validates_email :email # client side validation of email address

  # override Devise method
  # no password is required when the account is created; validate password when the user sets one
  validates_confirmation_of :password
  #def password_required?
  #  if !persisted?
  #    !(password != "")
  #  else
  #    !password.nil? || !password_confirmation.nil?
  #  end
  #end

  # override Devise method so that people joining the waiting list don't get invited yet
  #def confirmation_required?
  #  false
  #end

  # override Devise method
  def active_for_authentication?
    confirmed? || confirmation_period_valid?
  end

  def send_reset_password_instructions
    if self.confirmed?
      super
    else
      errors.add :base, "You must receive an invitation before you set your password."
    end
  end

  def mailboxer_email(object)
    # TODO check user preferences to see if they want notifications
    # if wants_notifications
    return self.email
    # else
    #   nil
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = User.find(current_user)
    @spaces = Space.where(user_id: current_user)
    render 'show'
  end

  def show
    @user = User.find(params[:id])
    @spaces = Space.where(user_id: params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
      
    end
  end
end

app/views/users/_modals.html.haml
#messageModal.reveal-modal.small
  = simple_form_for Message.new do |f|
    = f.input :recipient, as: :hidden, input_html: { value: @user }
    = f.input :subject, as: :hidden, input_html: { value: "Inquiry about your spaces" }
    = f.input_field :body, as: :text, label: 'Message'
    = f.button :submit, 'Send', class: "button fullbtn radius"
  %a.close-reveal-modal
    %i.icon-remove-circle

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :validate => true, :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
.row
  %h3 users
  .large-8
    %table.table.table-condensed
      %thead
        %tr
          %th username
          %th email
          %th registered
          %th spaces
          %th role
          %th
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.name, user
            %td= user.email
            %td= user.created_at.to_date
            %td= link_to Space.by_user(user).count, user_spaces_path(user)
            %td= user.roles.first.name.titleize unless user.roles.first.nil?
            %td
              %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
              = render user
            %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
.row
  .large-4.medium-5.columns
    #owner.well.clearfix
      - if @user.avatar.exists?
        = image_tag @user.avatar.url(:square)
      %h3
        = @user.name
      - if @user != current_user
        = link_to 'javascript:;', {class: 'button fullbtn radius standard', "data-reveal-id" => "messageModal"} do
          %i{:class=>'icon-envelope'}
          Message

      - if can_edit_user?(@user)
        = link_to edit_user_registration_path, {:class=>'button radius fullbtn standard'} do
          %i{:class=>'icon-pencil'}
          Edit Profile
    %p.show-for-medium-down
      =@user.bio
  .large-8.medium-7.columns
    .hide-for-medium-down
      %p
        =@user.bio
      %hr
    - @spaces.each do |s|
      .bigtime{:style => "background-image: url(#{s.photo if s.photo.exists?})"}
        = link_to space_path(s) do
          .bigprice
            .dollars
              %sup $
              #{s.monthly_price}
            .small per month
        .shade
          %h2
            = link_to space_path(s) do
              #{s.title}
            %sup
              %i.icon-map-marker
              #{s.city}, #{s.state}
              - if can_edit_space?(s)
                |
                = link_to edit_space_path(s), { :class=>'', :title => 'Edit Your Listing' } do
                  Edit
          %ul.features.clearfix
            - if s.environment? == "indoor"
              %li.has-tip{ data: { tooltip: 'Indoors' }, title: 'Indoors' }
                .ico-home
            - elsif s.environment == "outdoor"
              %li.has-tip{ data: { tooltip: 'Outdoors' }, title: 'Outdoors' }
                .ico-tree
            - if s.type?
              - if s.type == "attic"
                %li.has-tip{ data: { tooltip: 'Attic' }, title: 'Attic' }
                  .ico-flashlight
              - elsif s.type == "spare_room"
                %li.has-tip{ data: { tooltip: 'Spare Room' }, title: 'Spare Room' }
                  .ico-dolly
              - elsif s.type == "garage"
                %li.has-tip{ data: { tooltip: 'Garage' }, title: 'Garage' }
                  .ico-drill
              - elsif s.type == "basement"
                %li.has-tip{ data: { tooltip: 'Basement' }, title: 'Basement' }
                  .ico-travel
              - elsif s.type == "covered"
                %li.has-tip{ data: { tooltip: 'Covered' }, title: 'Covered' }
                  .ico-trailer
              - elsif s.type == "uncovered"
                %li.has-tip{ data: { tooltip: 'Uncovered' }, title: 'Uncovered' }
                  .ico-acorn
              - elsif s.type == "driveway"
                %li.has-tip{ data: { tooltip: 'Driveway' }, title: 'Driveway' }
                  .icon-road
            - if s.access?
              - if s.access == "anytime"
                %li.has-tip{ data: { tooltip: 'Anytime Access' }, title: 'Anytime Access' }
                  .ico-open
              - elsif s.access == "appointment"
                %li.has-tip{ data: { tooltip: 'Appointment Access' }, title: 'Appointment Access' }
                  .ico-clock
              - elsif s.access == "limited"
                %li.has-tip{ data: { tooltip: 'Limited Access' }, title: 'Limited Access' }
                  .ico-bolt
            - if s.climate_controlled?
              %li.has-tip{ data: { tooltip: 'Climate Controlled' }, title: 'Climate Controlled' }
                .ico-equalizer
            - if s.lockable?
              %li.has-tip{ data: { tooltip: 'Lockable' }, title: 'Lockable' }
                .ico-locked
            - if s.attended?
              %li.has-tip{ data: { tooltip: 'Attended' }, title: 'Attended' }
                .ico-tie
= render 'users/modals'