config/routes.rb
StowAway::Application.routes.draw do
  
  
  get '/admin/billing_events' => 'admin#billing_events' # TODO move to rails_admin custom action
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    resources :charges
    resources :spaces, only: [:index]
  end

  post '/api/stripe_webhook' => 'webhook#record_stripe_webhook' 
  
  resources :spaces
  resources :messages, as: 'messages'

  get 'terms' => 'home#terms'

  get 'search' => 'search#index'

  get "/login" => redirect("/users/sign_in")

  mount Blogit::Engine => "/blog"

  
  get '/orders/subregion_options' => 'orders#subregion_options'
end

app/views/blogit/posts/_active_record_comments.html.erb
<div id="comments">
  <%= render post.comments %>
</div>
<%= render partial: "blogit/comments/form", locals: { post: post, comment: comment } %>

app/views/blogit/posts/_blog_post_spacer.html.erb
<hr class="blog_post_spacer">

app/views/blogit/posts/_blogger_information.html.erb
<%= blog_tag :footer do %>
    <%=t :written_by, scope: 'blogit.posts', author: post.blogger_display_name %>
    <%= time_tag(post.created_at, pubdate: true, format: blogit_conf.datetime_format) %>
    <a href="http://stowaway.uservoice.com" data-uv-trigger>Contact us</a>﻿﻿
<% end %>

app/views/blogit/posts/_comments_count.html.erb
<%= content_tag(:div, class: "blog_post_comments_count", id: "blog_post_#{post.id}_comments_count") do %>
  <%= link_to(post_path(post, anchor: "comments")) do %>
    <%=t :comment, scope: 'blogit.posts', count: post.comments_count %>
  <% end %>
<% end %>

app/views/blogit/posts/_disqus_comments.html.erb
 <div id="disqus_thread"></div>
 <script type="text/javascript">
   /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
   var disqus_shortname = '<%= Blogit.configuration.disqus_shortname %>'; // required: replace example with your forum shortname

   /* * * DON'T EDIT BELOW THIS LINE * * */
   (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '<%= request.protocol %>' + disqus_shortname + '.disqus.com/embed.js?<%= request.protocol_name %>';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/blogit/posts/_empty.html.erb
<div class="blogit_empty_message">
  <%=t :there_are_no_posts_about, scope: 'blogit.posts', tag: params[:tag] %>
</div>

app/views/blogit/posts/_form.html.erb
<%= form_for(@post, html: {class: "new_blog_post", id: "new_blog_post"}) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%=t :prohibited_this_post_from_being_saved, scope: 'blogit.posts', count: @post.errors.count%></h2>

      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= field do %>
      <%= f.text_field :title, placeholder: t(:give_your_post_a_title, scope: 'blogit.posts') %>
    <% end %>

    <%= field do %>
      <%= f.text_area :body, placeholder: t(:write_something_here, scope: 'blogit.posts') %>
    <% end %>
  </fieldset>

  <fieldset>

    <%= field id: "new_blog_post_tag_field" do %>
      <%= f.label :tag_list, t(:tags, scope: 'blogit.posts') %>
      <%= f.text_field :tag_list, placeholder: t(:tag_placeholder, scope: 'blogit.posts') %>
    <% end %>

    <p class="blog_post_tip">
      <strong>Tip:</strong> You can style your post using <a href="http://daringfireball.net/projects/markdown/syntax">Markdown</a>.
    </p>

  </fieldset>

  <%= actions do %>
    <%= f.submit :class => "button radius"%> <%=t :or, scope: 'blogit.posts'%>
    <%= link_to(t(:cancel, scope: 'blogit.posts'), @post.new_record? ? blog_root_path : post_path(@post)) %>
  <% end %>

<% end %>

app/views/blogit/posts/_pagination.html.erb
<%= paginate(@posts) %>

app/views/blogit/posts/_post.html.erb
<%= content_tag(:article, id: "blog_post_#{post.id}", class: "blog_post") do %>

  <%# Render the header for this blog post %>
  <%= render "blogit/posts/post_head", post: post %>

  <%# Render the body of this blog post (as Markdown) %>
  <%= render "blogit/posts/post_body", post: post %>

  <%# Render admin links to edit/delete this post %>
  <%= render "blogit/posts/post_links", post: post %>

  <%# Render info about the person who wrote this post %>
  <%= render "blogit/posts/blogger_information", post: post %>

  <%# Render the no. of comments %>
  <%= render "blogit/posts/comments_count",
    post: post if defined?(show_comments_count) and show_comments_count %>

<% end %>

app/views/blogit/posts/_post_links.html.erb
<%= login_required do  %>
  <%= actions do %>
    <%= link_to(t(:edit, scope: 'blogit.posts'), edit_post_path(post)) %> | <%= link_to(t(:delete, scope: 'blogit.posts'), post, method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_post, scope: 'blogit.posts')) %>
  <% end %>
<% end unless blogit_conf.author_edits_only and not this_blogger?(post) %>

app/views/blogit/posts/_share_bar.html.erb
<div id="blog_share_bar">

  <div id="google-plus" class="social_button">
    <!-- GOOGLE +1 -->
    <g:plusone size="medium"></g:plusone>
    <script type="text/javascript">
      window.___gcfg = {lang: '<%= I18n.default_locale %>'};

      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- /GOOGLE +1 -->
  </div>

  <div id="twitter" class="social_button">
    <!-- TWITTER -->
    <a href="https://twitter.com/share" class="twitter-share-button"
        data-lang="<%= I18n.default_locale %>"
        data-url="http://<%= request.host_with_port %><%= request.path.gsub("//","/") %>"
        data-via="<%= Blogit.configuration.twitter_username %>"
        data-text="<%= post.title%>"
        data-count="horizontal">Tweet</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <!-- /TWITTER -->
  </div>

  <div id="facebook" class="social_button">
    <!-- FACEBOOK LIKE -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/<%= t "blogit.share_bar.facebook" %>/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-like" data-send="false"  data-layout="button_count" data-width="90" data-show-faces="false"></div>
    <!-- /FACEBOOK LIKE -->
  </div>

</div>

app/views/blogit/posts/edit.html.erb
<h2><%=t :edit_blog_post, scope: 'blogit.posts', id: @post.id %></h2>

<%= render 'form' %>

app/views/blogit/posts/new.html.erb
<h2>Write a New Post</h2>

<%= render 'form' %>

app/views/blogit/posts/show.html.erb
<%= render @post %>
<%= share_bar_for @post %>
<%= render "blogit/posts/post_footer", post: @post %>
<%= comments_for @post %>