config/routes.rb
StowAway::Application.routes.draw do
  
  
  get '/admin/billing_events' => 'admin#billing_events' # TODO move to rails_admin custom action
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users do
    resources :charges
    resources :spaces, only: [:index]
  end

  post '/api/stripe_webhook' => 'webhook#record_stripe_webhook' 
  
  resources :spaces
  resources :messages, as: 'messages'

  get 'terms' => 'home#terms'

  get 'search' => 'search#index'

  get "/login" => redirect("/users/sign_in")

  mount Blogit::Engine => "/blog"

  
  get '/orders/subregion_options' => 'orders#subregion_options'
end

app/views/layouts/_avatar.small.html.haml
- if current_user.avatar.exists?
  = image_tag current_user.avatar.url(:thumb)
- else
  = image_tag "http://placehold.it/50x50", :class => "avatar"

app/views/layouts/_footer.html.haml
.row.text-center
  %ul.inline-list.social
    %li.github
      %a{:href => "https://github.com/stowawayco/stowaway", :target => "_blank"}
        %i.icon-github
    %li.startup_portland
      %a{:href => "http://startupportland.com", :target => "_blank"}
        %i.sp-icon

= yield :scripts

= javascript_include_tag "https://checkout.stripe.com/v2/checkout.js"

// Include the UserVoice JavaScript SDK (only needed once on a page)
:javascript
  UserVoice=window.UserVoice||[];(function(){
  var uv=document.createElement('script');
  uv.type='text/javascript';uv.async=true;
  uv.src='//widget.uservoice.com/vllXVJfPHhTCcx9YSEeAg.js';
  var s=document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(uv,s)})();
  // Set colors

  UserVoice.push(['set', {
    accent_color: '#448dd6',
    trigger_color: 'white',
    trigger_background_color: 'rgba(46, 49, 51, 0.6)',
    contact_title: 'Beta users: Please list a space, and tell us how it went.',
    smartvote_title: 'What should we build next?'
  }]);

  // Add default trigger to the bottom-right corner of the window:
  UserVoice.push(['addTrigger', { mode: 'contact', trigger_position: 'bottom-right' }]);

  // Or, use your own custom trigger:
  //UserVoice.push(['addTrigger', '#id', { mode: 'contact' }]);

  // Autoprompt for Satisfaction and SmartVote (only displayed under certain conditions)
  UserVoice.push(['autoprompt', {}]);

  // Send data to customer.io
  var _cio = _cio || [];
  (function() {
    var a,b,c;a=function(f){return function(){_cio.push([f].
    concat(Array.prototype.slice.call(arguments,0)))}};b=["load","identify",
    "sidentify","track","page"];for(c=0;c<b.length;c++){_cio[b[c]]=a(b[c])};
    var t = document.createElement('script'),
        s = document.getElementsByTagName('script')[0];
    t.async = true;
    t.id    = 'cio-tracker';
    t.setAttribute('data-site-id', '651d1b138e624dcc2e52');
    t.src = 'https://assets.customer.io/assets/track.js';
    s.parentNode.insertBefore(t, s);
  })();

- if user_signed_in?
  - current_user_email = current_user.email
  - current_user_name = current_user.name
  - current_user_created_at = current_user.created_at.to_i
  - current_user_id = current_user.id
  - outdoor_listing_count = Space.by_user_outdoor(current_user).count
  - indoor_listing_count = Space.by_user_indoor(current_user).count
  - total_listing_count = Space.by_user(current_user).count
  - active_listing_count = Space.by_user(current_user).available.count
  - has_avatar = current_user.avatar.exists?
  - sent_message_count = current_user.mailbox.sentbox.count
  :javascript
    UserVoice.push(['identify', {
      email: '#{current_user_email}',
      name: '#{current_user_name}'}
    ]);
    // Identify the user and pass traits
    // To enable, replace sample data with actual user traits and uncomment the line
    //UserVoice.push(['identify', {
      //email:      'john.doe@example.com', // User’s email address
      //name:       'John Doe', // User’s real name
      //created_at: 1364406966, // Unix timestamp for the date the user signed up
      //id:         123, // Optional: Unique id of the user (if set, this should not change)
      //type:       'Owner', // Optional: segment your users by type
      //account: {
      //  id:           123, // Optional: associate multiple users with a single account
      //  name:         'Acme, Co.', // Account name
      //  created_at:   1364406966, // Unix timestamp for the date the account was created
      //  monthly_rate: 9.99, // Decimal; monthly rate of the account
      //  ltv:          1495.00, // Decimal; lifetime value of the account
      //  plan:         'Enhanced' // Plan name for the account
      //}
    //}]);

    // customer.io identification
    _cio.identify({
      id: '#{current_user_id}',
      email: '#{current_user_email}',
      created_at: '#{current_user_created_at}',
      name: '#{current_user_name}',
      outdoor_listing_count: '#{outdoor_listing_count}',
      indoor_listing_count: '#{indoor_listing_count}',
      total_listing_count: '#{total_listing_count}',
      active_listing_count: '#{active_listing_count}',
      has_avatar: '#{has_avatar}',
      sent_message_count: '#{sent_message_count}'
    });

:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43750203-1', 'stowaway.co');
  ga('send', 'pageview');

:javascript
  $(document).ready(function() {
    if( $('.gmaps4rails_map').length > 0 ) {
      google.maps.visualRefresh=true;
      Gmaps.loadMaps();
    }
  });

:javascript
  $(document).ready(function(){
    $("label").inFieldLabels({
      pollDuration: 100
    });
  });

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.contain-to-grid
  %nav.top-bar
    %ul.title-area
      %li.name
        .logo
          = link_to "stowaway.co", root_path
          %small.beta beta
    %section.top-bar-section
      %ul.right
        - if user_signed_in?
          %li.has-dropdown
            = link_to user_path(current_user), id: 'account' do
              = render 'layouts/avatar.small'
              %span
                = current_user.name
            %ul.dropdown
              %li
                = link_to user_path(current_user) do
                  %i.icon-dashboard
                  Dashboard
              %li
                = link_to user_spaces_path(current_user) do
                  %i.icon-tasks
                  Listings
              %li
                = link_to messages_path do
                  %i.icon-envelope
                  Messages
              %li
                = link_to edit_user_registration_path(current_user) do
                  %i.icon-pencil
                  Edit Profile
              - if current_user.has_role? :admin
                %li
                  = link_to rails_admin_path do
                    %i.icon-cogs
                    Admin
              %li
                = link_to destroy_user_session_path, :method=>'delete' do
                  %i.icon-power-off
                  Sign Out
        - else
          %li
            = link_to 'Sign up', new_user_registration_path
        %li
          = link_to 'Help', 'http://stowaway.uservoice.com/'
        %li.abtn
          %a.button.radius{:href => spaces_path}
            %i.icon-search.icon-left.icon-muted
            %span Find
        %li.abtn.last
          %a.button.radius{:href => new_space_path}
            %i.icon-plus.icon-left.icon-muted
            %span List
  %a.menu-link{:href=>'#'}
    %i.icon-reorder

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Stowaway"
      %meta{:content => content_for?(:description) ? yield(:description) : "Stowaway", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        %link{ type: "text/css", rel: "stylesheet", href: "//fonts.googleapis.com/css?family=Quicksand:400,700|Open+Sans+Condensed:300,700|Dosis:300,400,500,600,700" }
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .push
      = render 'layouts/navigation'
      #main{:role => "main"}
        .row
          .columns
            .box
              = render 'layouts/messages'
              = yield
        #f_shiv
      %footer#footer
        = render 'layouts/footer'
        / ! end of #container
    - if user_signed_in?
      %nav#menu.panel.shade{role: 'navigation'}
        %ul
          %li.abtn
            %a.button.radius.expand{:href => spaces_path}
              %i.icon-search.icon-left.icon-muted
              %span Find a Space
          %li.abtn.last
            %a.button.radius.expand{:href => new_space_path}
              %i.icon-plus.icon-left.icon-muted
              %span List a Space
          %li.has-dropdown
            = link_to user_path(current_user), id: 'account' do
              = render 'layouts/avatar.small'
              %span
                = current_user.name
            %ul.dropdown
              %li
                = link_to user_path(current_user) do
                  %i.icon-dashboard
                  Dashboard
              %li
                = link_to user_spaces_path(current_user) do
                  %i.icon-tasks
                  My Listings
              %li
                = link_to messages_path do
                  %i.icon-envelope
                  My Messages
              %li
                = link_to user_charges_path(current_user) do
                  %i.icon-money
                  My Charges
              %li
                = link_to edit_user_registration_path(current_user) do
                  %i.icon-pencil
                  Edit Profile
              - if current_user.has_role? :admin
                %li
                  = link_to rails_admin_path do
                    %i.icon-cogs
                    Admin
              %li
                = link_to destroy_user_session_path, :method=>'delete' do
                  %i.icon-power-off
                  Sign Out

app/views/layouts/prelaunchlayout.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Stowaway"
      %meta{:content => content_for?(:description) ? yield(:description) : "Stowaway", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        /= google_webfonts_link_tag :quicksand => [400,700], :open_sans_condensed => [300,700], :dosis => [300,400,500,600,700]
        %link{ type: "text/css", rel: "stylesheet", href: "//fonts.googleapis.com/css?family=Quicksand:400,700|Open+Sans+Condensed:300,700|Dosis:300,400,500,600,700" }
        = yield(:head)
  %body{:class => "prelaunch #{controller_name} #{action_name}"}
    #main{:role => "main"}
      = render 'layouts/messages'
      = yield
      #f_shiv
  %footer#footer
    = render 'layouts/footer'
  / ! end of #container